[tool.poetry]
name = "polus-tabular-transforms-feature-concat"
version = "0.1.0-dev4"
description = "Concatenate Nyxus channel features from multiple files, rename channels, and associate metadata."
authors = [
"Hamdah Shafqat abbasi <hamdahshafqat.abbasi@nih.gov>"
]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9"
typer = "^0.7.0"
filepattern = "^2.0.5"
pyarrow = ">=16.0,<17.0"
pandas = "^2.2.3"


[tool.poetry.group.dev.dependencies]
bump2version = "^1.0.1"
pre-commit = "^3.1.0"
black = "^23.1.0"
flake8 = "^6.0.0"
mypy = "^1.0.1"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
